### ISSUE TITLE
Facing Issue while copying content 

### ISSUE THREAD

**Issue by bhaveshmodiatekaplus** [SumoLogic/sumologictoolbox#7]
For Copying content i am facing below issues.
1) While copying  Global Folder  that copy button is disabled. 
2) While copying Personal folder , in tool its showing folder transferred, but after login it is not showing any folder or dashboard.

**Comment by voltaire321** [comment]
1. This a not yet implemented. You can enter a user folder and copy content from/into it but you cannot copy user folders at the root level. 
2. Where you copying to an admin recommended folder? What version of the tool are you using? There was a bug that required the admin folder contents to be shared to be visible but that has been fixed in recent versions.
